### ISSUE TITLE
any Idea for reimport?

### ISSUE THREAD

**Issue by YouKnow-sys** [Bl00drav3n/CryXmlB#1]
Hi thank you for your work, its perfect, but do you have any Idea to import xml back to binary??

**Comment by Bl00drav3n** [comment]
Hey! I don't remember from the top of my head, but I think there should be some resource compiler that's part of the cry engine: [https://docs.cryengine.com/display/CEMANUAL/Binary+XML+Conversion](https://docs.cryengine.com/display/CEMANUAL/Binary+XML+Conversion)
My code doesn't support converting it back into binary format, but it should be fairly easy to just revert all the operations done.
